### ISSUE TITLE
Django syncdb error with PostgreSQL

### ISSUE THREAD

**Issue by webs86** [jqb/django-settings#19]
Hi,
when I try syncdb with PostgreSQL 9.3.3 I get this error:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "c:\pyprojects\mg\lib\site-packages\django\core\management__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "c:\pyprojects\mg\lib\site-packages\django\core\management__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\pyprojects\mg\lib\site-packages\django\core\management\base.py", line 242, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "c:\pyprojects\mg\lib\site-packages\django\core\management\base.py", line 284, in execute
    self.validate()
  File "c:\pyprojects\mg\lib\site-packages\django\core\management\base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "c:\pyprojects\mg\lib\site-packages\django\core\management\validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\loading.py", line 196, in get_app_errors
    self._populate()
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "c:\pyprojects\mg\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\pyprojects\mg\src\accounts\models.py", line 36, in <module>
    UserProfile._meta.get_field('codice_fiscale').blank=not django_settings.get('field_codice_fiscale_obb')
  File "c:\pyprojects\mg\lib\site-packages\django_settings\dataapi.py", line 36, in __call__
    return super(dataapi_get_method_proxy, self).**call**(name)
  File "c:\pyprojects\mg\lib\site-packages\django_settings\cache.py", line 81, in **call**
    origin_value = self.origin_method(_args, *_kwargs)
  File "c:\pyprojects\mg\lib\site-packages\django_settings\cache.py", line 64, in origin_method
    return self.method(self.instance, _args, *_kwargs)
  File "c:\pyprojects\mg\lib\site-packages\django_settings\dataapi.py", line 86, in get
    return db.Setting.objects.get_value(name, *_kw)
  File "c:\pyprojects\mg\lib\site-packages\django_settings\models.py", line 25, in get_value
    return self.get(name=name).setting_object.value
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\manager.py", line 151, in get
    return self.get_queryset().get(_args, **kwargs)
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\query.py", line 301, in get
    num = len(clone)
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\query.py", line 77, in **len**
    self._fetch_all()
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\sql\compiler.py", line 709, in results_iter
    for rows in self.execute_sql(MULTI):
  File "c:\pyprojects\mg\lib\site-packages\django\db\models\sql\compiler.py", line 782, in execute_sql
    cursor.execute(sql, params)
  File "c:\pyprojects\mg\lib\site-packages\django\db\backends\util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "c:\pyprojects\mg\lib\site-packages\django\db\backends\util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "c:\pyprojects\mg\lib\site-packages\django\db\utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "c:\pyprojects\mg\lib\site-packages\django\db\backends\util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ERRORE:  la relazione "django_settings_setting" non esiste
LINE 1: ...etting_id", "django_settings_setting"."name" FROM "django_se...

**Comment by ygneo** [comment]
Same problem here, using django-settings 1.3-11, Django==1.6.6 and postgres 9.3.5
